Tslint prettier
welovecoding/welovecoding pull request #23
Opened 2017-06-08 13:47 UTC by TN1ck

## Tslint
Finally Some linting is there! I also added a pre-commit hook to disallow any commits that contain linting errors.
I use the same config `/tslint.json` for frontend and backend.

## Prettier
I also added prettier, there are no hooks yet, but I formatted the code once with it.

I also fixed issues that were triggered by the new linting.

As a bonus I added source-map support for the backend so one can see where an error actually occured.

2017-06-08 20:08 UTC, bennycode requested changes

2017-06-08 20:08 UTC, bennyn commented on tslint.json
> +    // TODO: these should be activated at one point
There are no comments in JSON.

2017-06-08 20:08 UTC, bennyn commented on tslint.json
> +    "ordered-imports": [false],
Does it need an array or would `"ordered-imports": false` be sufficient?

2017-06-08 20:08 UTC, bennyn commented on frontend/package.json
> +    "tslint": "^5.2.0",
We should go for fix versions (`5.2.0`).

2017-06-08 20:08 UTC, bennyn commented on backend/package.json
> +    "prettier": "^1.4.4",
As long as we don't use yarn I would always go for fixed versions.

2017-06-08 20:08 UTC, bennyn commented on backend/package.json
> +    "prettier:base": "prettier --parser typescript --single-quote --trailing-comma='all' --no-bracket-spacing",
Do we need 3 prettier scripts? Isn't just one (with `--write`) enough?)

2017-06-09 09:37 UTC, TN1ck commented on tslint.json
> +    // TODO: these should be activated at one point
It works though as is normally done like this, see the tslint.json from the maintainers of tslint: https://github.com/palantir/tslint/blob/master/tslint.json

2017-06-09 09:38 UTC, TN1ck commented on tslint.json
> +    "ordered-imports": [false],
Needs an array or at least the type-checking of the file says so

2017-06-09 09:38 UTC, TN1ck commented on backend/package.json
> +    "prettier:base": "prettier --parser typescript --single-quote --trailing-comma='all' --no-bracket-spacing",
I adopted this schema from somewhere else. It makes it a bit better looking imho

2017-06-09 09:38 UTC, TN1ck commented on backend/package.json
> +    "prettier": "^1.4.4",
Correct

2017-06-09 09:38 UTC, TN1ck commented on frontend/package.json
> +    "tslint": "^5.2.0",
Correct

2017-06-09 14:37 UTC, bennycode approved these changes

2017-06-09 15:08 UTC, bennyn commented on tslint.json
> +    // TODO: these should be activated at one point
We should have more dignity than these TSLint barbarians. 😁 There are no comments allowed in JSON (https://jsonlint.com/ will show the truth). Let's be professional programmers who don't misuse well-defined standards. 🌵

2017-06-09 15:08 UTC, bennyn commented on tslint.json
> +    "ordered-imports": [false],
ok!

2017-06-09 15:09 UTC, bennyn commented on frontend/package.json
> +    "tslint": "^5.2.0",
Ok, then this needs pinning too. At the moment only backend properties are pinned.

2017-06-09 15:11 UTC, bennycode requested changes

2017-06-09 15:11 UTC, bennyn commented on backend/package.json
> +    "prettier:base": "prettier --parser typescript --single-quote --trailing-comma='all' --no-bracket-spacing",
But is there a need for `prettier:base` and `prettier:check`? Isn't just `prettier:write` enough?

2017-06-14 12:59 UTC, bennycode approved these changes

2017-06-14 15:21 UTC, merged