Test setup for legacy REST API mapping (categories)
welovecoding/welovecoding pull request #25
Opened 2017-06-08 23:34 UTC by bennyn

## Setup

I created basic entity layers (Data Transfer Objects) to mimic We Love Coding's first API release. These DTOs should be replaced by our Sequelize models in a later PR.

For API testing I created an initial setup using [Jasmine](https://jasmine.github.io/) and [supertest](https://github.com/visionmedia/supertest).

## Scope

Scope of this PR is to make `npm test` work and to add a mapping for the categories (and just the categories) of WLC's first REST API, which is available here: www.welovecoding.com/rest/service/v1/categories

Mapping for Playlists, Videos, etc. will follow later.

## Required help

@TN1ck, to test our server I need to import it using `const server = require('../dist/Server');`. At the current stage this is only possible when compiling our backend source code using `tsc`. If I use `webpack`, then a huge `main.js` will pop out which cannot be required that easily. Do you have any recommendation on how to export our server with webpack?

In addition, should we use TypeScript for out tests too or are you fine having pure ES6 in this case?

2017-06-09 11:49 UTC, TN1ck requested changes
Cool work!
I don't know if you want to do it, but I __really__ would use Jest instead of Jasmine, then it's also possible to write the tests in TypeScript and the importing issues etc go away. I did setup Jest in a TS project once, so I can do it if you want.

The super strong OO pattern you used here makes sense if it's the direct translation of the Java Code. In general I'm more the FP guy and would express the logic differently, but it makes sense here to just translate the old code.

I guess the relative imports are because of Jasmine? History showed me, that relative imports should be avoided at all costs :smile:

2017-06-09 11:49 UTC, TN1ck commented on backend/src/models/index.ts
> +import db from '../config/database';
Why?

2017-06-09 11:49 UTC, TN1ck commented on backend/src/api/v1/dto/CategoryDTO.ts
> +    return numberOfVideos;
```js
return this._playlists.reduce((current: number, playlist: PlaylistDTO) => current + playlist.numberOfVideos);
```
or
```js
return _.sumBy(this._playlists, 'numberOfVideos');
```

2017-06-09 11:49 UTC, TN1ck commented on backend/src/api/v1/dto/CategoryDTO.ts
> +  get playlists(): Array<PlaylistDTO> {
Why bother with pseudo private stuff a la `_field` when the get/set is public?

2017-06-09 11:49 UTC, TN1ck commented on backend/src/api/v1/dto/BaseDTO.ts
> +  get slug(): string {
This should actually be an utility function, that could be used here.

2017-06-09 11:49 UTC, TN1ck commented on backend/src/Server.ts
> +import User from './models/User';
Why all these relative imports? I only allow `./ONE_LEVEL.ts` :smile:

2017-06-09 11:49 UTC, TN1ck commented on backend/package.json
> +    "jasmine": "2.6.0",
We should use Jest instead of Jasmine. Jest has really nice TypeScript support and amazing testing capabilites for React. It's super mature by now.

2017-06-09 11:49 UTC, TN1ck commented on backend/src/api/v1/dto/CategoryDTO.ts
> +// https://github.com/bennyn/wlc-webapp/blob/wlc-webapp/0.0.36/src/main/java/com/welovecoding/tutorial/api/v1/dto/CategoryDTO.java
aah ok, that explains the OO-pattern used here, I was wondering if you translated the Java Code.

2017-06-09 11:49 UTC, TN1ck commented on backend/src/api/v1/dto/CategoryDTO.ts
> +  get numberOfVideos(): number {
Honestly. I don't like when fields/functions are called the same way. It looks clean and cool to write `playlist.numberOfVideos`, but is it good to give the programmer the illusion of a static field? What do you think?

2017-06-09 15:14 UTC, bennyn commented on backend/src/models/index.ts
> +import db from '../config/database';
It doesn't work with absolute paths. I am getting the following error when using `'src/config/database'`:

```js
Error: Cannot find module 'src/config/database'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\dev\projects\welovecoding\welovecoding\backend\dist\models\index.js:4:20)
```

Steps to reproduce:

```bash
cd backend
tsc
node dist/index.js
```

2017-06-09 15:16 UTC, bennyn commented on backend/src/api/v1/dto/CategoryDTO.ts
> +  get numberOfVideos(): number {
I agree with you but that's the way JavaScript getters work. They are functions but can be called like properties.

2017-06-09 15:16 UTC, bennyn commented on backend/src/api/v1/dto/CategoryDTO.ts
> +    return numberOfVideos;
Naaah. For such a trivial task we don't need a third party library like "underscore".

2017-06-09 15:21 UTC, bennyn commented
## Jasmine <> Jest

I am okay with using Jest but then I need your help setting it up. :)

## Object-Oriented Programming Concept

Yeah, I just translated the old Java code here. The code will change once we switch from DTO's to the Entity models of Sequelize.

## static vs. relative imports

I turned the static imports into relative imports because it fails otherwise:

```javascript
Error: Cannot find module 'src/config/database'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\dev\projects\welovecoding\welovecoding\backend\dist\models\index.js:4:20)
```

2017-06-09 15:22 UTC, bennyn commented on backend/src/api/v1/dto/BaseDTO.ts
> +  get slug(): string {
Good call! Actually I wanted to a pre-existing library for that. Any suggestions?

2017-06-14 15:17 UTC, TN1ck commented
I switched to jest, the test now pass and the imports are working fine :)
https://github.com/welovecoding/welovecoding/tree/rest-api-v1-jest

2017-06-14 16:48 UTC, TN1ck commented
Closed because of #28 .

2017-06-14 16:48 UTC, closed without merging